# Site settings
title: Phusion Models International
email: phusionmodels@gmail.com
description: "Phusion Models International"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/phusionmodels
  - title: github
    url: http://github.com/phusionmodels
  - title: envelope
    url: mailto:phusionmodels@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: Kingston.
  - line: Jamaica, West Indies

# Build settings
markdown: kramdown
permalink: pretty
